#!/usr/bin/env python3
import csv
import statistics
import sys
from collections import defaultdict


def main(summary_path, output_path):
    rows = []
    with open(summary_path, newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            rows.append(row)

    grouped = defaultdict(list)
    for row in rows:
        key = (row['graph_type'], row['algorithm'])
        grouped[key].append(float(row['elapsed_ms']))

    graph_types = sorted({k[0] for k in grouped})
    algorithms = sorted({k[1] for k in grouped})

    with open(output_path, 'w') as out:
        out.write('% Auto-generated by generate_report.py\n')
        out.write('\\section{Experiments}\n')
        out.write('\\begin{table}[h]\n')
        out.write('\\centering\n')
        out.write('\\begin{tabular}{l' + 'c' * len(algorithms) + '}\n')
        out.write('\\toprule\n')
        header = 'Graph Type & ' + ' & '.join(algorithms) + ' \\\\n'
        out.write(header)
        out.write('\\midrule\n')
        for graph_type in graph_types:
            row = [graph_type]
            for algorithm in algorithms:
                values = grouped.get((graph_type, algorithm), [])
                if values:
                    mean_ms = statistics.mean(values)
                    row.append(f'{mean_ms:.2f}')
                else:
                    row.append('--')
            out.write(' & '.join(row) + ' \\\\\\n')
        out.write('\\bottomrule\n')
        out.write('\\end{tabular}\n')
        out.write('\\caption{BMSSP framework benchmark summary.}\n')
        out.write('\\end{table}\n')
